### ISSUE TITLE
Can't start mysql server

### ISSUE THREAD

**Issue by mdzidic** [adamcooke/staytus#177]
Hello,
I'm trying to start Staytus docker image via Docker Compose and I'm experiencing this error:

> Starting MySQL database server: mysqld . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . failed!
> 12:02:19 worker.1 | [Worker(host:6a8d53609dc8 pid:755)] Starting job worker
> 12:02:19 worker.1 | [Worker(host:6a8d53609dc8 pid:755)] Error while reserving job: Can't connect to MySQL server on '127.0.0.1' (111)
> 12:03:04 worker.1 | rake aborted!
> 12:03:04 worker.1 | Mysql2::Error: Can't connect to MySQL server on '127.0.0.1' (111)
> 12:03:04 worker.1 | /opt/staytus/vendor/bundle/ruby/2.2.0/gems/mysql2-0.3.18/lib/mysql2/client.rb:70:in `connect'
> 12:03:04 worker.1 | /opt/staytus/vendor/bundle/ruby/2.2.0/gems/mysql2-0.3.18/lib/mysql2/client.rb:70:in `initialize'
...

staytus.yml
```yaml
version: "2"
services:
  staytus:
    image: adamcooke/staytus
    ports:
      - 5000:5000
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/staytus:/opt/staytus/persisted
    restart: always
```

It seems there is problem when I try to persist data manually...
