### ISSUE TITLE
PostgreSQL or SQLite support?

### ISSUE THREAD

**Issue by jcgruenhage** [adamcooke/staytus#200]
It would be great if Staytus was a little more flexible on the database side of things.

**Comment by phonicmouse** [comment]
+1 for postgres

**Comment by psvmcc** [comment]
Example for SQLite:

```
git clone https://github.com/adamcooke/staytus
cd staytus
sed -i -e 's/mysql2 (.*/sqlite3 (1.3.11)/g' Gemfile.lock
sed -i -e 's/mysql2/sqlite3/g’ Gemfile Gemfile.lock
```

Then edit __config/database.yml__
```
default: &default
  adapter: sqlite3
  database: _db.sqlite3
  timeout: 5000
production:
  <<: *default
development:
  <<: *default
```

And after
```
bundle install --deployment --without development:test
bundle exec rake staytus:build staytus:install
```
