### ISSUE TITLE
Mysql2::Error: Access denied for user

### ISSUE THREAD

**Issue by tb582** [adamcooke/staytus#261]
Seem to be stuck at this install step
```
`Mysql2::Error: Access denied for user 'staytus'@'localhost' (using password: YES)
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:89:in `connect'
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:89:in `initialize'
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/mysql2_adapter.rb:21:in `new'
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/mysql2_adapter.rb:21:in `mysql2_connection'
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:759:in `new_connection'
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:803:in `checkout_new_connection'
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:782:in `try_to_checkout_new_connection'
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:743:in `acquire_connection'
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:500:in `checkout'
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:374:in `connection'
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `retrieve_connection'
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_handling.rb:116:in `retrieve_connection'
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_handling.rb:88:in `connection'
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:1038:in `current_version'
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:1271:in `last_stored_environment'
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/tasks/database_tasks.rb:56:in `check_protected_environments!'
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/railties/databases.rake:11:in `block (2 levels) in <top (required)>'
/opt/staytus/.rbenv/versions/2.5.1/bin/bundle:23:in `load'
/opt/staytus/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
Tasks: TOP => staytus:install => db:schema:load => db:check_protected_environments
(See full trace by running task with --trace)
```
`
Even though I've verified that my staytus user can login with the creds listed in the yml??? 

Here's my config/database.yml 
```
`
# Database configuration for Staytus.
#
# By default, Staytus works with a MySQL database. While
# it may work with other engines, they are untested and
# currently unsupported. You can make changes to this file
# to specify the database to connect to.

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: staytus
  password: *****
  database: staytus
  host: 127.0.0.1

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
#  database: staytus_test`
```
